name: Reusable workflow for tests

on:
  workflow_call:
    inputs:
      work_dir:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      test_command:
        required: true
        type: string
      run_after_job:
        required: true
        type: string
     
jobs:
  run_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.work_dir }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        id: download
        with:
          name: ${{ inputs.artifact_name }}
      - name: Prepare executable
        run: |
          mv ${{steps.download.outputs.download-path}}/program.sh .
          chmod +x program.sh
      - name: Run tests
        run: ${{ inputs.test_command }}


  