name: Compile
on: [push]
jobs:
  build-sequential:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/sequential
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies 
        run: make ubuntu_install
      - name: Compile
        run: make compile
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: sequential.sh
          path: src/sequential/program.sh
          if-no-files-found: error

  build-parallel:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/parallel
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies 
        run: make ubuntu_install
      - name: Compile
        run: make compile
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: parallel.sh
          path: src/parallel/program.sh
          if-no-files-found: error

  test-sequential:
    uses: ./.github/workflows/test_reusable.yml
    needs: [build-sequential]
    with: 
      work_dir: src/sequential
      artifact_name: sequential.sh
      test_command:  make test
      
  test-parallel-1-core:
    uses: ./.github/workflows/test_reusable.yml
    needs: [build-parallel]
    with: 
      work_dir: src/parallel
      artifact_name: parallel.sh
      test_command:  make test_1
  
  test-parallel-2-core:
    uses: ./.github/workflows/test_reusable.yml
    needs: [build-parallel]
    with: 
      work_dir: src/parallel
      artifact_name: parallel.sh
      test_command:  make test_2

  test-parallel-4-core:
    uses: ./.github/workflows/test_reusable.yml
    needs: [build-parallel]
    with: 
      work_dir: src/parallel
      artifact_name: parallel.sh
      test_command:  make test_4